source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'mysql2', '~> 0.2.7'
gem 'rake', '~> 0.8.7'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'ar-extensions'
gem 'bluecloth'
gem 'will_paginate'
gem 'validates_timeliness'
gem 'paperclip'
gem 'formtastic'
gem 'authlogic'
gem 'meta_where'
gem 'meta_search'
gem 'cornell_netid'
gem 'whenever'
gem 'declarative_authorization'
gem 'jquery-rails'
gem 'rails3-jquery-autocomplete'
group :development, :test do
  gem 'launchy'
  gem 'test-unit'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
  gem 'factory_girl', '1.3.2'
  gem "pickle"
end

